# ‚òÄÔ∏è suntrack-py Example Notebook

This notebook demonstrates how to use the `tts_data_client` library to query the Tracking-the-Sun dataset.

---

## üõ†Ô∏è Setup

It's recommended to use a virtual environment for this project. In a terminal, run:

```bash
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

If you want progress bars, also install tqdm:

```bash
pip install tqdm
```
```

---

**Cell 2: Code (Import the client)**
```python
from tts_data_client import TTSClient
```

---

**Cell 3: Markdown (Basic Query)**
```markdown
## üîç Basic Query: 2019 California Data
```

---

**Cell 4: Code (Basic Query)**
```python
client = TTSClient()
df_ca2019 = client.query(year=2019, state="CA")
df_ca2019.head()
```

---

**Cell 5: Markdown (List Available Fields)**
```markdown
## üìã List Available Fields
```

---

**Cell 6: Code (List Fields)**
```python
fields = client.get_fields(year=2019, state="CA")
fields
```

---

**Cell 7: Markdown (Filter by System Size)**
```markdown
## üìä Filter by System Size (> 5000)
```

---

**Cell 8: Code (Filter by System Size)**
```python
df_large = client.query(year=2019, state="CA", field_filters={"system_size": (">", 5000)})
df_large.head()
```

---

**Cell 9: Markdown (Filter by Technology)**
```markdown
## ‚òÄÔ∏è Filter by Technology (e.g., CSP)
```

---

**Cell 10: Code (Filter by Technology)**
```python
df_csp = client.query(year=2019, state="CA", field_filters={"module_technology_1": ("==", "CSP")})
df_csp.head()
```

---

**Cell 11: Markdown (Multi-Year, Multi-State Query)**
```markdown
## üåé Multi-Year, Multi-State Query
```

---

**Cell 12: Code (Multi-Year, Multi-State Query)**
```python
df_multi = client.query(year=[2018, 2019], state=["CA", "AZ"])
df_multi.head()
```

---

**Cell 13: Markdown (Helper Methods)**

In [3]:
# Get Package
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))
from tts_data_client import TTSClient

## üîç Basic Query: 2019 California Data

In [4]:
client = TTSClient()
df_ca2019 = client.query(year=2019, state="CA")
df_ca2019.head()

Year 2019, State CA: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2019/state=CA/part-00065-bc1e8188-aa98-424a-9051-d92e72ddaa77.c000.snappy.parquet ...
Concatenating data frames...
Done.

,data_provider,system_id_from_first_data_provider,system_id_from_second_data_provider_if_applicable,system_id_tracking_the_sun,installation_date,system_size,total_installed_price,appraised_value_flag,sales_tax_cost,rebate_or_grant,...,inverter_manufacturer_3,inverter_model_1,inverter_model_2,inverter_model_3,microinverter_1,microinverter_2,microinverter_3,system_inverter_capacity,dc_optimizer,inverter_loading_ratio
0,California Center for Sustainable Energy (Bear...,BVSI-0041,-9999,CA_Xka6Fzjs3g,2014-07-09,7.000,-9999.0,False,-9999.000000,4294.0,...,-9999,-9999,-9999,-9999,1,-9999,-9999,3.36,0,2.083333
1,California Public Utilities Commission,SDGE-INT-90038,-9999,CA_mWQvE7526g,2015-09-28,5.600,19600.0,False,585.874851,0.0,...,-9999,m250-60-2ll-s2x -zc -na 240v,-9999,-9999,1,-9999,-9999,4.80,0,1.166667
2,California Center for Sustainable Energy (Bear...,BVSI-0049,-9999,CA_yNdEyYYnJL,2015-02-04,6.600,-9999.0,False,-9999.000000,5418.0,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999.00,0,-9999.000000
3,California Public Utilities Commission,SDGE-INT-90039,-9999,CA_URKiDn4PBz,2015-10-28,9.156,43426.0,False,957.905381,0.0,...,-9999,sb7700tl-us-22-240v,-9999,-9999,0,-9999,-9999,7.00,0,1.308000
4,California Center for Sustainable Energy (Bear...,BVSI-0050,-9999,CA_vFi13b2YJh,2015-02-04,4.400,-9999.0,False,-9999.000000,5655.0,...,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999.00,0,-9999.000000

## üìã List Available Fields

In [6]:
fields = client.get_fields(year=2019, state="CA")
fields

['data_provider',
 'system_id_from_first_data_provider',
 'system_id_from_second_data_provider_if_applicable',
 'system_id_tracking_the_sun',
 'installation_date',
 'system_size',
 'total_installed_price',
 'appraised_value_flag',
 'sales_tax_cost',
 'rebate_or_grant',
 'performance_based_incentive_annual_payment',
 'performance_based_incentives_duration',
 'feed_in_tariff_annual_payment',
 'feed_in_tariff_duration',
 'customer_segment',
 'new_construction',
 'tracking',
 'ground_mounted',
 'battery_system',
 'zip_code',
 'city',
 'utility_service_territory',
 'third_party_owned',
 'installer_name',
 'self_installed',
 'azimuth_1',
 'azimuth_2',
 'azimuth_3',
 'tilt_1',
 'tilt_2',
 'tilt_3',
 'module_manufacturer_1',
 'module_model_1',
 'module_manufacturer_2',
 'module_model_2',
 'module_manufacturer_3',
 'module_model_3',
 'additional_module_model',
 'module_technology_1',
 'module_technology_2',
 'module_technology_3',
 'bipv_module_1',
 'bipv_module_2',
 'bipv_module_3',
 'module_efficiency_1',
 'module_efficiency_2',
 'module_efficiency_3',
 'inverter_manufacturer_1',
 'inverter_manufacturer_2',
 'inverter_manufacturer_3',
 'inverter_model_1',
 'inverter_model_2',
 'inverter_model_3',
 'microinverter_1',
 'microinverter_2',
 'microinverter_3',
 'system_inverter_capacity',
 'dc_optimizer',
 'inverter_loading_ratio']

## üìä EXAMPLE: Filter by System Size (> 5000)

In [8]:
df_large = client.query(year=2019, state="CA", field_filters={"system_size": (">", 5000)})
df_large.head()

Year 2019, State CA: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2019/state=CA/part-00065-bc1e8188-aa98-424a-9051-d92e72ddaa77.c000.snappy.parquet ...
Concatenating data frames...
Applying filters...
Filtering system_size > 5000
Done.

,data_provider,system_id_from_first_data_provider,system_id_from_second_data_provider_if_applicable,system_id_tracking_the_sun,installation_date,system_size,total_installed_price,appraised_value_flag,sales_tax_cost,rebate_or_grant,...,inverter_manufacturer_3,inverter_model_1,inverter_model_2,inverter_model_3,microinverter_1,microinverter_2,microinverter_3,system_inverter_capacity,dc_optimizer,inverter_loading_ratio
41349,Sacramento Municipal Utility District,CP-00676,-9999,CA_TRwhDFp0mA,2016-04-06,6454.200,-9999.0,True,-9999.0,1032425.0,...,-9999,sgi 750xtm,-9999,-9999,0,-9999,-9999,5313.0,0,1.214794
717943,Sacramento Municipal Utility District,CP-00676,-9999,CA_TRwhDFp0mA,2016-04-06,6454.200,-9999.0,True,-9999.0,1032425.0,...,-9999,sgi 750xtm,-9999,-9999,0,-9999,-9999,5313.0,0,1.214794
751616,California Public Utilities Commission,PGE-INT-114206275,-9999,CA_seuOTlzlOn,2017-11-01,13305.615,-9999.0,False,-9999.0,0.0,...,SMA America,sc800cp-us,sc900cp-us w/ abb xfmr,stp24000tl-us-10 480v,0,0,0,8560.0,0,1.554394

## üåé Multi-Year, Multi-State Query

In [9]:
df_multi = client.query(year=[2018, 2019], state=["CA", "AZ"])
df_multi.head()

Year 2018, State CA: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2018/state=CA/part-00065-f1bfe925-7995-4be1-8ce7-1bcb5c01bdbd.c000.snappy.parquet ...
Year 2018, State AZ: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2018/state=AZ/part-00004-f1bfe925-7995-4be1-8ce7-1bcb5c01bdbd.c000.snappy.parquet ...
Year 2019, State CA: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2019/state=CA/part-00065-bc1e8188-aa98-424a-9051-d92e72ddaa77.c000.snappy.parquet ...
Year 2019, State AZ: Found 1 files. Loading up to 1...
Loading oedi-data-lake/tracking-the-sun/2019/state=AZ/part-00004-bc1e8188-aa98-424a-9051-d92e72ddaa77.c000.snappy.parquet ...
Concatenating data frames...
Done.

,data_provider,system_id_from_data_provider,system_id_tracking_the_sun,installation_date,system_size,total_installed_price,appraised_value_flag,sales_tax_cost,rebate_or_grant,performance_based_incentive_annual_payment,...,inverter_quantity_3,additional_inverter_model,microinverter_1,microinverter_2,microinverter_3,dc_optimizer,system_id_from_first_data_provider,system_id_from_second_data_provider_if_applicable,system_inverter_capacity,inverter_loading_ratio
0,Public Utilities Commission & California Energ...,PGE-INT-10,CA-NEM-1,2002-08-21,2.880000,-9999.0,False,-9999.000000,-9999.0,0.0,...,-9999.0,0.0,0,-9999,-9999,0,NaN,NaN,NaN,NaN
1,Public Utilities Commission & California Energ...,SCE-INT-500564244,CA-NEM-424769,2014-08-19,5.612245,-9999.0,False,-9999.000000,0.0,0.0,...,-9999.0,0.0,0,-9999,-9999,0,NaN,NaN,NaN,NaN
2,Public Utilities Commission & California Energ...,PGE-INT-100,CA-NEM-2,2002-11-15,4.435200,-9999.0,False,-9999.000000,-9999.0,0.0,...,-9999.0,0.0,0,-9999,-9999,0,NaN,NaN,NaN,NaN
3,Public Utilities Commission & California Energ...,SCE-INT-500564245,CA-NEM-424770,2014-06-30,5.163265,-9999.0,True,-9999.000000,0.0,0.0,...,-9999.0,0.0,0,-9999,-9999,0,NaN,NaN,NaN,NaN
4,Public Utilities Commission & California Energ...,PGE-INT-1000 & 7999.0,CA-NEM-3,2003-05-02,3.000000,24000.0,False,1237.358958,11137.5,0.0,...,-9999.0,-9999.0,0,-9999,-9999,0,NaN,NaN,NaN,NaN